language: python
python:
  - "2.7"
  - "3.2"
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y python-opencv
  - pip install -r requirements.txt
  - pip install codecov
script:
  - py.test --cov=.
after_success:
  - codecov
virtualenv:
  system_site_packages: true
