language: python
python:
  - "2.7"
  - "3.2"
sudo: false
addons:
  apt:
    packages:
      - python-opencv
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - py.test
after_success:
  - py.test --cov=avena
  - codecov
virtualenv:
  system_site_packages: true
