#!/usr/bin/env python

'''Avena - an image processing tool

Usage:
    avena filter (high|low) <radius> <image>...
    avena flip (vertical|horizontal) <image>...
    avena -h | --help
    avena -v | --version

Options:
    -h, --help      Print this help.
    -v, --version   Print version information.
'''


from __future__ import print_function

from docopt import docopt

from avena import avena, image
from avena import filter, flip


long_version = 'Avena ' + avena.__version__


if __name__ == '__main__':

    arguments = docopt(__doc__, version=long_version)

    files = list(arguments['<image>'])
    images = (image.read(i) for i in arguments['<image>'])

    image.SAVE_NORMALIZED = True

    if arguments['filter']:

        radius = int(arguments['<radius>'])
        for filename, img in zip(files, images):
            if arguments['high']:
                filtered_img = filter.highpass(img, radius)
            elif arguments['low']:
                filtered_img = filter.lowpass(img, radius)
            print(image.save(filtered_img, filename, random=True))

    elif arguments['flip']:

        if arguments['vertical']:
            flip_func = flip.flip_vertical
        else:
            flip_func = flip.flip_horizontal
        for filename, img in zip(files, images):
            flipped_img = flip_func(img)
            print(image.save(flipped_img, filename, random=True))
