#!/usr/bin/env python2

'''Avena - an image processing tool

Usage:
    avena -h | --help
    avena -v | --version

Options:
    -h, --help      Print this help.
    -v, --version   Print version information.
'''


from docopt import docopt

from avena import avena


long_version = 'Avena ' + avena.__version__


if __name__ == '__main__':

    arguments = docopt(__doc__, version=long_version)
