#!/usr/bin/env python

'''Avena - an image processing tool

Usage:
    avena filter (high|low) <radius> <image>...
    avena -h | --help
    avena -v | --version

Options:
    -h, --help      Print this help.
    -v, --version   Print version information.
'''


from __future__ import print_function

from docopt import docopt

from avena import avena, filter, image


long_version = 'Avena ' + avena.__version__


if __name__ == '__main__':

    arguments = docopt(__doc__, version=long_version)

    if arguments['filter']:
        radius = int(arguments['<radius>'])
        for i in list(arguments['<image>']):
            img = image.read(i)
            if arguments['high']:
                filtered_img = filter.highpass(img, radius)
            elif arguments['low']:
                filtered_img = filter.lowpass(img, radius)
            print(image.save(filtered_img, i, random=True, normalize=True))
